package edu.pitt.cs.cs1635.mypantry.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import edu.pitt.cs.cs1635.mypantry.model.Recipe;
import edu.pitt.cs.cs1635.mypantry.model.Item;
import edu.pitt.cs.cs1635.mypantry.model.RecipeItem;

import edu.pitt.cs.cs1635.mypantry.model.RecipeDao;
import edu.pitt.cs.cs1635.mypantry.model.ItemDao;
import edu.pitt.cs.cs1635.mypantry.model.RecipeItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recipeDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig recipeItemDaoConfig;

    private final RecipeDao recipeDao;
    private final ItemDao itemDao;
    private final RecipeItemDao recipeItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recipeDaoConfig = daoConfigMap.get(RecipeDao.class).clone();
        recipeDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        recipeItemDaoConfig = daoConfigMap.get(RecipeItemDao.class).clone();
        recipeItemDaoConfig.initIdentityScope(type);

        recipeDao = new RecipeDao(recipeDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        recipeItemDao = new RecipeItemDao(recipeItemDaoConfig, this);

        registerDao(Recipe.class, recipeDao);
        registerDao(Item.class, itemDao);
        registerDao(RecipeItem.class, recipeItemDao);
    }
    
    public void clear() {
        recipeDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        recipeItemDaoConfig.getIdentityScope().clear();
    }

    public RecipeDao getRecipeDao() {
        return recipeDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public RecipeItemDao getRecipeItemDao() {
        return recipeItemDao;
    }

}
