package edu.pitt.cs.cs1635.mypantry.model;

import edu.pitt.cs.cs1635.mypantry.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECIPE_ITEM".
 */
public class RecipeItem {

    private Long recipeId;
    private Long itemId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RecipeItemDao myDao;

    private Recipe recipe;
    private Long recipe__resolvedKey;

    private Item item;
    private Long item__resolvedKey;


    public RecipeItem() {
    }

    public RecipeItem(Long recipeId, Long itemId) {
        this.recipeId = recipeId;
        this.itemId = itemId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRecipeItemDao() : null;
    }

    public Long getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(Long recipeId) {
        this.recipeId = recipeId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /** To-one relationship, resolved on first access. */
    public Recipe getRecipe() {
        Long __key = this.recipeId;
        if (recipe__resolvedKey == null || !recipe__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RecipeDao targetDao = daoSession.getRecipeDao();
            Recipe recipeNew = targetDao.load(__key);
            synchronized (this) {
                recipe = recipeNew;
            	recipe__resolvedKey = __key;
            }
        }
        return recipe;
    }

    public void setRecipe(Recipe recipe) {
        synchronized (this) {
            this.recipe = recipe;
            recipeId = recipe == null ? null : recipe.getId();
            recipe__resolvedKey = recipeId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Item getItem() {
        Long __key = this.itemId;
        if (item__resolvedKey == null || !item__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ItemDao targetDao = daoSession.getItemDao();
            Item itemNew = targetDao.load(__key);
            synchronized (this) {
                item = itemNew;
            	item__resolvedKey = __key;
            }
        }
        return item;
    }

    public void setItem(Item item) {
        synchronized (this) {
            this.item = item;
            itemId = item == null ? null : item.getId();
            item__resolvedKey = itemId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
